import type { ModelConfigMap } from './model';

export const DEFAULT_MODELS: ModelConfigMap = {
	// anthropic models
	'claude-opus-4-5-20251101': {
		inputCostPerMillion: 5.0,
		outputCostPerMillion: 25.0,
		cacheCostPerMillion: 0.5,
		contextWindow: 200000,
		description: 'Claude Opus 4.5',
	},
	'claude-sonnet-4-5-20250929': {
		inputCostPerMillion: 3.0,
		outputCostPerMillion: 15.0,
		cacheCostPerMillion: 0.3,
		contextWindow: 200000,
		description: 'Claude Sonnet 4.5',
	},
	'claude-haiku-4-5-20251001': {
		inputCostPerMillion: 1.0,
		outputCostPerMillion: 5.0,
		cacheCostPerMillion: 0.1,
		contextWindow: 200000,
		description: 'Claude Haiku 4.5',
	},
	'claude-opus-4-1-20250805': {
		inputCostPerMillion: 15.0,
		outputCostPerMillion: 75.0,
		cacheCostPerMillion: 1.5,
		contextWindow: 200000,
		description: 'Claude Opus 4.1',
	},
	'claude-sonnet-4-20250514': {
		inputCostPerMillion: 3.0,
		outputCostPerMillion: 15.0,
		cacheCostPerMillion: 0.3,
		contextWindow: 200000,
		description: 'Claude Sonnet 4',
	},
	'claude-opus-4-20250514': {
		inputCostPerMillion: 15.0,
		outputCostPerMillion: 75.0,
		cacheCostPerMillion: 1.5,
		contextWindow: 200000,
		description: 'Claude Opus 4',
	},
	'claude-3-7-sonnet-20250219': {
		inputCostPerMillion: 3.0,
		outputCostPerMillion: 15.0,
		cacheCostPerMillion: 0.3,
		contextWindow: 200000,
		description: 'Claude Sonnet 3.7',
	},
	'claude-3-5-haiku-20241022': {
		inputCostPerMillion: 0.8,
		outputCostPerMillion: 4.0,
		cacheCostPerMillion: 0.08,
		contextWindow: 200000,
		description: 'Claude Haiku 3.5',
	},
	'claude-3-haiku-20240307': {
		inputCostPerMillion: 0.25,
		outputCostPerMillion: 1.25,
		cacheCostPerMillion: 0.03,
		contextWindow: 200000,
		description: 'Claude Haiku 3',
	},

	// openai models
	'gpt-5.2': {
		inputCostPerMillion: 1.75,
		outputCostPerMillion: 14.0,
		cacheCostPerMillion: 0.175,
		contextWindow: 400000,
		description: 'GPT-5.2 - Flagship model for coding and agentic tasks',
	},
	'gpt-5.2-pro': {
		inputCostPerMillion: 21.0,
		outputCostPerMillion: 168.0,
		contextWindow: 400000,
		description: 'GPT-5.2 pro - Higher compute GPT-5.2',
	},
	'gpt-5.1': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 0.125,
		contextWindow: 400000,
		description: 'GPT-5.1 - Configurable reasoning flagship model',
	},
	'gpt-5': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 0.125,
		contextWindow: 400000,
		description: 'GPT-5 - Previous flagship reasoning model',
	},
	'gpt-5-mini': {
		inputCostPerMillion: 0.25,
		outputCostPerMillion: 2.0,
		cacheCostPerMillion: 0.025,
		contextWindow: 400000,
		description: 'GPT-5 mini - Fast, cost-efficient GPT-5',
	},
	'gpt-5-nano': {
		inputCostPerMillion: 0.05,
		outputCostPerMillion: 0.4,
		cacheCostPerMillion: 0.005,
		contextWindow: 400000,
		description: 'GPT-5 nano - Fastest, most cost-efficient GPT-5',
	},
	'gpt-5-pro': {
		inputCostPerMillion: 15.0,
		outputCostPerMillion: 120.0,
		contextWindow: 400000,
		description: 'GPT-5 pro - Higher compute GPT-5',
	},
	'gpt-5.2-chat-latest': {
		inputCostPerMillion: 1.75,
		outputCostPerMillion: 14.0,
		cacheCostPerMillion: 0.175,
		contextWindow: 128000,
		description: 'GPT-5.2 Chat - ChatGPT snapshot',
	},
	'gpt-5.1-chat-latest': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 0.125,
		contextWindow: 128000,
		description: 'GPT-5.1 Chat - ChatGPT snapshot',
	},
	'gpt-5-chat-latest': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 0.125,
		contextWindow: 128000,
		description: 'GPT-5 Chat - ChatGPT snapshot',
	},
	'gpt-5.1-codex-max': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 0.125,
		contextWindow: 400000,
		description: 'GPT-5.1 Codex Max - Long-horizon coding model',
	},
	'gpt-5.1-codex': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 0.125,
		contextWindow: 400000,
		description: 'GPT-5.1 Codex - Codex-optimized GPT-5.1',
	},
	'gpt-5.1-codex-mini': {
		inputCostPerMillion: 0.25,
		outputCostPerMillion: 2.0,
		cacheCostPerMillion: 0.025,
		contextWindow: 400000,
		description: 'GPT-5.1 Codex mini - Smaller Codex model',
	},
	'gpt-5-codex': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 0.125,
		contextWindow: 400000,
		description: 'GPT-5 Codex - Codex-optimized GPT-5',
	},
	'codex-mini-latest': {
		inputCostPerMillion: 1.5,
		outputCostPerMillion: 6.0,
		cacheCostPerMillion: 0.375,
		contextWindow: 200000,
		description: 'codex-mini-latest - Codex CLI optimized model',
	},
	'gpt-5-search-api': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 0.125,
		contextWindow: 400000,
		description: 'GPT-5 Search API - Context window assumed same as GPT-5',
	},
	'gpt-4.1': {
		inputCostPerMillion: 2.0,
		outputCostPerMillion: 8.0,
		cacheCostPerMillion: 0.5,
		contextWindow: 1047576,
		description: 'GPT-4.1 - Smartest non-reasoning model',
	},
	'gpt-4.1-mini': {
		inputCostPerMillion: 0.4,
		outputCostPerMillion: 1.6,
		cacheCostPerMillion: 0.1,
		contextWindow: 1047576,
		description: 'GPT-4.1 mini - Smaller, faster GPT-4.1',
	},
	'gpt-4.1-nano': {
		inputCostPerMillion: 0.1,
		outputCostPerMillion: 0.4,
		cacheCostPerMillion: 0.025,
		contextWindow: 1047576,
		description: 'GPT-4.1 nano - Fastest, most cost-efficient GPT-4.1',
	},
	'gpt-4o': {
		inputCostPerMillion: 2.5,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 1.25,
		contextWindow: 128000,
		description: 'GPT-4o - Fast, intelligent, flexible GPT model',
	},
	'gpt-4o-2024-05-13': {
		inputCostPerMillion: 5.0,
		outputCostPerMillion: 15.0,
		contextWindow: 128000,
		description: 'GPT-4o snapshot (2024-05-13)',
	},
	'gpt-4o-mini': {
		inputCostPerMillion: 0.15,
		outputCostPerMillion: 0.6,
		cacheCostPerMillion: 0.075,
		contextWindow: 128000,
		description: 'GPT-4o mini - Fast, affordable small model',
	},
	'gpt-4o-audio-preview': {
		inputCostPerMillion: 2.5,
		outputCostPerMillion: 10.0,
		contextWindow: 128000,
		description: 'GPT-4o Audio preview - Text token rates; audio tokens priced separately',
	},
	'gpt-4o-mini-audio-preview': {
		inputCostPerMillion: 0.15,
		outputCostPerMillion: 0.6,
		contextWindow: 128000,
		description: 'GPT-4o mini Audio preview - Text token rates; audio tokens priced separately',
	},
	'gpt-audio': {
		inputCostPerMillion: 2.5,
		outputCostPerMillion: 10.0,
		contextWindow: 128000,
		description: 'gpt-audio - Text token rates; audio tokens priced separately',
	},
	'gpt-audio-mini': {
		inputCostPerMillion: 0.6,
		outputCostPerMillion: 2.4,
		contextWindow: 128000,
		description: 'gpt-audio-mini - Text token rates; audio tokens priced separately',
	},
	'gpt-4o-realtime-preview': {
		inputCostPerMillion: 5.0,
		outputCostPerMillion: 20.0,
		cacheCostPerMillion: 2.5,
		contextWindow: 32000,
		description: 'GPT-4o Realtime preview - Text token rates; audio tokens priced separately',
	},
	'gpt-4o-mini-realtime-preview': {
		inputCostPerMillion: 0.6,
		outputCostPerMillion: 2.4,
		cacheCostPerMillion: 0.3,
		contextWindow: 16000,
		description: 'GPT-4o mini Realtime preview - Text token rates; audio tokens priced separately',
	},
	'gpt-realtime': {
		inputCostPerMillion: 4.0,
		outputCostPerMillion: 16.0,
		cacheCostPerMillion: 0.5,
		contextWindow: 32000,
		description: 'gpt-realtime - Text token rates; audio/image tokens priced separately',
	},
	'gpt-realtime-mini': {
		inputCostPerMillion: 0.6,
		outputCostPerMillion: 2.4,
		cacheCostPerMillion: 0.06,
		contextWindow: 32000,
		description: 'gpt-realtime-mini - Text token rates; audio/image tokens priced separately',
	},
	'gpt-4o-search-preview': {
		inputCostPerMillion: 2.5,
		outputCostPerMillion: 10.0,
		contextWindow: 128000,
		description: 'GPT-4o Search Preview - Web search model',
	},
	'gpt-4o-mini-search-preview': {
		inputCostPerMillion: 0.15,
		outputCostPerMillion: 0.6,
		contextWindow: 128000,
		description: 'GPT-4o mini Search Preview - Web search model',
	},
	'computer-use-preview': {
		inputCostPerMillion: 3.0,
		outputCostPerMillion: 12.0,
		contextWindow: 8192,
		description: 'computer-use-preview - Computer use tool model',
	},
	o1: {
		inputCostPerMillion: 15.0,
		outputCostPerMillion: 60.0,
		cacheCostPerMillion: 7.5,
		contextWindow: 200000,
		description: 'o1 - Previous full o-series reasoning model',
	},
	'o1-mini': {
		inputCostPerMillion: 1.1,
		outputCostPerMillion: 4.4,
		cacheCostPerMillion: 0.55,
		contextWindow: 128000,
		description: 'o1-mini - Small reasoning model',
	},
	'o1-pro': {
		inputCostPerMillion: 150.0,
		outputCostPerMillion: 600.0,
		contextWindow: 200000,
		description: 'o1-pro - Higher compute o1',
	},
	o3: {
		inputCostPerMillion: 2.0,
		outputCostPerMillion: 8.0,
		cacheCostPerMillion: 0.5,
		contextWindow: 200000,
		description: 'o3 - Reasoning model for complex tasks',
	},
	'o3-mini': {
		inputCostPerMillion: 1.1,
		outputCostPerMillion: 4.4,
		cacheCostPerMillion: 0.55,
		contextWindow: 200000,
		description: 'o3-mini - Small reasoning model',
	},
	'o3-pro': {
		inputCostPerMillion: 20.0,
		outputCostPerMillion: 80.0,
		contextWindow: 200000,
		description: 'o3-pro - Higher compute o3',
	},
	'o3-deep-research': {
		inputCostPerMillion: 10.0,
		outputCostPerMillion: 40.0,
		cacheCostPerMillion: 2.5,
		contextWindow: 200000,
		description: 'o3-deep-research - Deep research model',
	},
	'o4-mini': {
		inputCostPerMillion: 1.1,
		outputCostPerMillion: 4.4,
		cacheCostPerMillion: 0.275,
		contextWindow: 200000,
		description: 'o4-mini - Fast, cost-efficient reasoning model',
	},
	'o4-mini-deep-research': {
		inputCostPerMillion: 2.0,
		outputCostPerMillion: 8.0,
		cacheCostPerMillion: 0.5,
		contextWindow: 200000,
		description: 'o4-mini-deep-research - Faster deep research model',
	},
	'gpt-4-turbo': {
		inputCostPerMillion: 10.0,
		outputCostPerMillion: 30.0,
		contextWindow: 128000,
		description: 'GPT-4 Turbo - Older high-intelligence GPT model',
	},
	'gpt-4': {
		inputCostPerMillion: 30.0,
		outputCostPerMillion: 60.0,
		contextWindow: 8192,
		description: 'GPT-4 - Older high-intelligence GPT model',
	},
	'gpt-3.5-turbo': {
		inputCostPerMillion: 0.5,
		outputCostPerMillion: 1.5,
		contextWindow: 16385,
		description: 'GPT-3.5 Turbo - Legacy GPT model',
	},
	'chatgpt-4o-latest': {
		inputCostPerMillion: 5.0,
		outputCostPerMillion: 15.0,
		contextWindow: 128000,
		description: 'ChatGPT-4o - GPT-4o model used in ChatGPT',
	},
	'gpt-image-1.5': {
		inputCostPerMillion: 5.0,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 1.25,
		contextWindow: 0,
		description: 'GPT Image 1.5 - Text token rates; image token pricing separate',
	},
	'chatgpt-image-latest': {
		inputCostPerMillion: 5.0,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 1.25,
		contextWindow: 0,
		description: 'ChatGPT Image Latest - Text token rates; image token pricing separate',
	},
	'gpt-image-1': {
		inputCostPerMillion: 5.0,
		outputCostPerMillion: 0.0,
		cacheCostPerMillion: 1.25,
		contextWindow: 0,
		description: 'GPT Image 1 - Text input tokens only; image token pricing separate',
	},
	'gpt-image-1-mini': {
		inputCostPerMillion: 2.0,
		outputCostPerMillion: 0.0,
		cacheCostPerMillion: 0.2,
		contextWindow: 0,
		description: 'GPT Image 1 mini - Text input tokens only; image token pricing separate',
	},

	// google models
	'gemini-3-pro-preview': {
		inputCostPerMillion: 2.0,
		outputCostPerMillion: 12.0,
		contextWindow: 1048576,
		description: 'Gemini 3 Pro Preview (<=200k prompt tier)',
	},
	'gemini-3-flash-preview': {
		inputCostPerMillion: 0.5,
		outputCostPerMillion: 3.0,
		contextWindow: 1048576,
		description: 'Gemini 3 Flash Preview',
	},
	'gemini-2.5-pro': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		contextWindow: 1048576,
		description: 'Gemini 2.5 Pro (<=200k prompt tier)',
	},
	'gemini-2.5-flash': {
		inputCostPerMillion: 0.3,
		outputCostPerMillion: 2.5,
		contextWindow: 1048576,
		description: 'Gemini 2.5 Flash',
	},
	'gemini-2.5-flash-preview-09-2025': {
		inputCostPerMillion: 0.3,
		outputCostPerMillion: 2.5,
		contextWindow: 1048576,
		description: 'Gemini 2.5 Flash Preview (09-2025)',
	},
	'gemini-2.5-flash-lite': {
		inputCostPerMillion: 0.1,
		outputCostPerMillion: 0.4,
		contextWindow: 1048576,
		description: 'Gemini 2.5 Flash-Lite',
	},
	'gemini-2.5-flash-lite-preview-09-2025': {
		inputCostPerMillion: 0.1,
		outputCostPerMillion: 0.4,
		contextWindow: 1048576,
		description: 'Gemini 2.5 Flash-Lite Preview (09-2025)',
	},
	'gemini-2.5-flash-native-audio-preview-12-2025': {
		inputCostPerMillion: 3.0,
		outputCostPerMillion: 12.0,
		contextWindow: 131072,
		description: 'Gemini 2.5 Flash Native Audio Preview (audio rates)',
	},
	'gemini-2.5-flash-preview-tts': {
		inputCostPerMillion: 0.5,
		outputCostPerMillion: 10.0,
		contextWindow: 8192,
		description: 'Gemini 2.5 Flash Preview TTS',
	},
	'gemini-2.5-pro-preview-tts': {
		inputCostPerMillion: 1.0,
		outputCostPerMillion: 20.0,
		contextWindow: 8192,
		description: 'Gemini 2.5 Pro Preview TTS',
	},
	'gemini-2.0-flash': {
		inputCostPerMillion: 0.1,
		outputCostPerMillion: 0.4,
		contextWindow: 1048576,
		description: 'Gemini 2.0 Flash',
	},
	'gemini-2.0-flash-lite': {
		inputCostPerMillion: 0.075,
		outputCostPerMillion: 0.3,
		contextWindow: 1048576,
		description: 'Gemini 2.0 Flash-Lite',
	},
	'gemini-2.5-computer-use-preview-10-2025': {
		inputCostPerMillion: 1.25,
		outputCostPerMillion: 10.0,
		contextWindow: 128000,
		description: 'Gemini 2.5 Computer Use Preview (<=200k prompt tier)',
	},
	'gemini-robotics-er-1.5-preview': {
		inputCostPerMillion: 0.3,
		outputCostPerMillion: 2.5,
		contextWindow: 1048576,
		description: 'Gemini Robotics-ER 1.5 Preview',
	},

	// xai models
	'grok-4-1-fast-reasoning': {
		inputCostPerMillion: 0.2,
		outputCostPerMillion: 0.5,
		contextWindow: 2000000,
		description: 'Grok 4.1 Fast (Reasoning)',
	},
	'grok-4-1-fast-non-reasoning': {
		inputCostPerMillion: 0.2,
		outputCostPerMillion: 0.5,
		contextWindow: 2000000,
		description: 'Grok 4.1 Fast (Non-Reasoning)',
	},
	'grok-code-fast-1': {
		inputCostPerMillion: 0.2,
		outputCostPerMillion: 1.5,
		contextWindow: 256000,
		description: 'Grok Code Fast 1',
	},
	'grok-4-fast-reasoning': {
		inputCostPerMillion: 0.2,
		outputCostPerMillion: 0.5,
		contextWindow: 2000000,
		description: 'Grok 4 Fast (Reasoning)',
	},
	'grok-4-fast-non-reasoning': {
		inputCostPerMillion: 0.2,
		outputCostPerMillion: 0.5,
		contextWindow: 2000000,
		description: 'Grok 4 Fast (Non-Reasoning)',
	},
	'grok-4-0709': {
		inputCostPerMillion: 3.0,
		outputCostPerMillion: 15.0,
		contextWindow: 256000,
		description: 'Grok 4 (0709)',
	},
	'grok-3-mini': {
		inputCostPerMillion: 0.3,
		outputCostPerMillion: 0.5,
		contextWindow: 131072,
		description: 'Grok 3 Mini',
	},
	'grok-3': {
		inputCostPerMillion: 3.0,
		outputCostPerMillion: 15.0,
		contextWindow: 131072,
		description: 'Grok 3',
	},
	'grok-2-vision-1212': {
		inputCostPerMillion: 2.0,
		outputCostPerMillion: 10.0,
		contextWindow: 32768,
		description: 'Grok 2 Vision (1212)',
	},

	// copilot models (unique ids)
	'claude-sonnet-4': {
		inputCostPerMillion: 3.0,
		outputCostPerMillion: 15.0,
		cacheCostPerMillion: 0.3,
		contextWindow: 200000,
		description: 'Claude Sonnet 4 (Copilot - estimated from Anthropic pricing)',
	},
	'claude-opus-4': {
		inputCostPerMillion: 15.0,
		outputCostPerMillion: 75.0,
		cacheCostPerMillion: 1.5,
		contextWindow: 200000,
		description: 'Claude Opus 4 (Copilot - estimated from Anthropic pricing)',
	},
	'claude-opus-4.5': {
		inputCostPerMillion: 5.0,
		outputCostPerMillion: 25.0,
		cacheCostPerMillion: 0.5,
		contextWindow: 200000,
		description: 'Claude Opus 4.5 (Copilot - estimated from Anthropic pricing)',
	},
	'claude-haiku-4.5': {
		inputCostPerMillion: 1.0,
		outputCostPerMillion: 5.0,
		cacheCostPerMillion: 0.1,
		contextWindow: 200000,
		description: 'Claude Haiku 4.5 (Copilot - estimated from Anthropic pricing)',
	},
	'gpt-5.2-high': {
		inputCostPerMillion: 2.5,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 1.25,
		contextWindow: 128000,
		description: 'GPT-5.2 High (Copilot - estimated from OpenAI pricing)',
	},
	'gpt-5.2-codex-high': {
		inputCostPerMillion: 2.5,
		outputCostPerMillion: 10.0,
		cacheCostPerMillion: 1.25,
		contextWindow: 128000,
		description: 'GPT-5.2 Codex High (Copilot - estimated from OpenAI pricing)',
	},
};
